---
  name: 'Client: Proof CI'
  on:
    workflow_dispatch:
      inputs:
        branch_name:
          description: 'Branch Name of Clients code to Clone'
          required: true
        extra_args:
          description: 'Additional Arguments to for run_kontro.sh '
          required: false
        statuses_sha:
          description: 'SHA of the commit to report status back to'
          required: false
        org:
          description: 'Organization to report statuses back to'
          required: false
        repository:
          description: 'Repository to report statuses back to'
          required: false
        auth_token:
          description: 'Auth Token w/ commit statuses permissions for reporting status'
          required: false
  
  # Stop in progress workflows on the same branch and same workflow to use latest committed code
  concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
  
  jobs:
    test-proofs:
      name: 'Test Proofs'
      runs-on: [self-hosted, linux, normal]
      steps:
        - name: 'Check out code'
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.JENKINS_GITHUB_PAT }}
            fetch-depth: 0

        - name: Report Pending Status
          run: |
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ github.event.inputs.auth_token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.event.inputs.org }}/${{ github.event.inputs.repository }}/statuses/${{ github.event.inputs.statuses_sha }} \
              -d '{"state":"pending","target_url":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}","description":"Proofs Pending","context":"runtimeverification/proof-runner"}'
 
        - name: "Install KaaS"
          uses: runtimeverification/install-kaas@v0.1.0
          with:
            github-token: ${{ secrets.JENKINS_GITHUB_PAT }}

        - name: "Download KCFG's"
          shell: bash
          run: |
            kaas-cli --vault ${{ secrets.CLIENT_VAULT }} --token ${{ secrets.CLIENT_TOKEN }} download -d kout-proofs/
    
        - name: 'Run Kontrol'
          run: |
            set -exou pipefail
            # Run the following in a docker container
            find . -name "run-kontrol.sh" -type f -exec {} ${{ github.event.inputs.extra_args }} \;

        - name: 'KCFG Upload Results'
          shell: bash
          run: |
            pushd optimism/packages/contracts-bedrock > /dev/null
            kaas-cli --vault ${{ secrets.CLIENT_VAULT }} --token ${{ secrets.CLIENT_TOKEN }} upload -d kout-proofs/
      
        - name: 'Upload Run results.tar.gz to summary'
          if: always()
          uses: actions/upload-artifact@v4.3.1
          with:
            name: Kontrol Results
            path: optimism/**/results-*.tar.gz
            retention-days: 5

        - name: Report Pass Status
          if: always() && success()
          run: |
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ github.event.inputs.auth_token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.event.inputs.org }}/${{ github.event.inputs.repository }}/statuses/${{ github.event.inputs.statuses_sha }} \
              -d '{"state":"success","target_url":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}","description":"Optimism Proof Execution Pending","context":"runtimeverification/optimism-ci"}'

        - name: Report Failure Status
          if: always() && failure()
          run: |
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.JENKINS_GITHUB_PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.event.inputs.org }}/${{ github.event.inputs.repository }}/statuses/${{ github.event.inputs.statuses_sha }} \
              -d '{"state":"failure","target_url":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}","description":"Optimism Proof Execution Pending","context":"runtimeverification/optimism-ci"}'
    