---
  name: 'Proof Runner'
  on:
    workflow_dispatch:
      inputs:
        branch_name:
          description: 'Branch Name of Clients code to Clone'
          required: true
          default: 'invariants'

  # Stop in progress workflows on the same branch and same workflow to use latest committed code
  concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.branch_name }}
    cancel-in-progress: false
  
  jobs:
    test-proofs:
      name: 'Test Proofs'
      runs-on: [self-hosted, linux, kaas]
      steps:
        - name: 'Check out code'
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.JENKINS_GITHUB_PAT }}
            fetch-depth: 0

        - name: Checkout CLIENT Code
          uses: actions/checkout@v4
          with:
            repository: 'runtimeverification/_audits_lidofinance_dual-governance_fork'
            path: '_audits_lidofinance_dual-governance_fork'
            ref: ${{ github.event.inputs.branch_name }}
            fetch-depth: 0
            submodules: 'recursive'
        
        - name: "Install KaaS"
          uses: runtimeverification/install-kaas@v0.2.1
          with:
            github-token: ${{ secrets.JENKINS_GITHUB_PAT }}

        - name: 'Run Kontrol'
          shell: bash
          run: |
            pushd _audits_lidofinance_dual-governance_fork/ > /dev/null
            export FOUNDRY_PROFILE=kontrol-properties 
            kaas-cli run -m remote --watch -t ${{ secrets.CLIENT_TOKEN }} --branch ${{ github.event.inputs.branch_name }}  -vs runtimeverification/_audits_lidofinance_dual-governance_fork 
