---
name: 'Client: LIDO'
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch Name to Test From'
        required: true
      extra_args:
        description: 'Additional Arguments to for run_kontro.sh '
        required: false
      statuses_sha:
        description: 'SHA of the commit to report back to'
        required: false
      org:
        description: 'Organization to run the test for'
        required: false
      repository:
        description: 'Repository to run the test for'
        required: false
      auth_token:
        description: 'GitHub PAT to use for API calls'
        required: false
    
# Multiple Runs will need to be allowed to queue
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.branch_name }}
  cancel-in-progress: true
    
jobs:
  lido:
    name: 'LIDO Kontrol CI'
    runs-on: [self-hosted, linux, kaas]
    env:
      GH_TOKEN: ${{ secrets.JENKINS_GITHUB_PAT}}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 'Check out code'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          fetch-depth: 0

      - name: Report Pending Status
        run: |
            curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.event.inputs.auth_token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{
              "state": "pending",
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "description": "Proofs Pending",
              "context": "runtimeverification/proof-runner"
            }' \
            https://api.github.com/repos/${{ github.event.inputs.org }}/${{ github.event.inputs.repository }}/statuses/${{ github.event.inputs.statuses_sha }}

      - name: "Install KaaS"
        uses: runtimeverification/install-kaas@v0.2.1
        with:
          github-token: ${{ secrets.JENKINS_GITHUB_PAT }}
                
      - name: "Checkout LIDO (RV Fork)"
        uses: actions/checkout@v4
        with:
          repository: '${{ github.event.inputs.org }}/${{ github.event.inputs.repository }}'
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          path: 'lido'
          ref: ${{ github.event.inputs.branch_name }}
          fetch-depth: 0
      #    submodules: 'recursive'

      # - name: Get Kontrol Version
      #   id: kontrol-version
      #   shell: bash
      #   run: |
      #     pushd lido
      #     echo "KONTROL_VERSION=$(cat test/kontrol/scripts/versions.json | jq -r .kontrol)" > "$GITHUB_OUTPUT"

      # - name: Install Kontrol
      #   uses: runtimeverification/install-kontrol@v1.0.2
      #   with:
      #     version: "v${{ steps.kontrol-version.outputs.KONTROL_VERSION }}"
      #     github-token: ${{ secrets.JENKINS_GITHUB_PAT }}
      - name: "Download KCFG Cache"
        shell: bash
        run: |
          pushd lido/ > /dev/null
          kaas-cli download --token ${{ secrets.LIDO_TOKEN }} -d ./kout/ runtimeverification/_audits_lidofinance_dual-governance_fork:latest
      - name: 'Run Kontrol'
        shell: bash
        run: |
          # Run the following in the running docker container
          pushd lido/ > /dev/null
          # Need to checkout submodules, GH action doesn't do this properly. 
          git submodule update --init --recursive
          # Lido uses npm to install OZ contracts, so won't be caught with git submodule
          npm install
          ./test/kontrol/scripts/run-kontrol.sh ${{ github.event.inputs.extra_args }}

      - name: 'Upload KCFG Cache Results to KaaS'
        if: always()
        run: |
          pushd lido/ > /dev/null
          CURRENT_COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "Current short commit SHA: $CURRENT_COMMIT_SHA"
          kaas-cli upload --token ${{ secrets.LIDO_TOKEN }} -d ./kout/ runtimeverification/_audits_lidofinance_dual-governance_fork:${{ github.event.inputs.statuses_sha}}
          kaas-cli upload --token ${{ secrets.LIDO_TOKEN }} -d ./kout/ runtimeverification/_audits_lidofinance_dual-governance_fork:latest

      - name: 'Upload KCFG Results to Summary'
        if: always()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Kontrol Results
          path: ./**/results-*.tar.gz
          retention-days: 5

      - name: Report Pass Status
        if: always() && success()
        run: |
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ github.event.inputs.auth_token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.event.inputs.org}}/${{ github.event.inputs.repository}}/statuses/${{ github.event.inputs.statuses_sha }} \
              -d '{
                "state": "success",
                "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "description": "Optimism Proof Execution Success",
                "context": "runtimeverification/proof-runner"
              }'
        
      - name: Report Failure Status
        if: always() && failure()
        run: |
            curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.event.inputs.auth_token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.event.inputs.org}}/${{ github.event.inputs.repository}}/statuses/${{ github.event.inputs.statuses_sha }} \
            -d '{
              "state": "failure",
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "description": "Proof Execution Failed",
              "context": "runtimeverification/proof-runner"
            }'
